export const words: { [key: string]: string[] } = {
  'en': [
    "apple", "ball", "cat", "dog", "egg", "fish", "hat", "ice", "jar", "kite",
    "lion", "moon", "nut", "owl", "pig", "rat", "sun", "toe", "urn", "van",
    "wax", "yak", "zip", "book", "cold", "duck", "frog", "gold", "herb", "iron",
    "joke", "knee", "leaf", "milk", "nose", "open", "pink", "quiz", "rose", "song",
    "tape", "unit", "vest", "wolf", "yawn", "zero", "apple", "banana", "cherry", "date",
    "elderberry", "fig", "grape", "honeydew", "kiwi", "lemon", "mango", "nectarine", "orange",
    "papaya", "quince", "raspberry", "strawberry", "tangerine", "watermelon", "airplane", "basketball",
    "baseball", "bicycle", "calculator", "calendar", "camera", "computer", "dictionary", "eraser", "furniture",
    "time", "ultra", "vent", "wall", "xenon", "yellow", "zebra", "window", "quartz",
    "violet", "umbrella", "treasure", "squirrel", "revolution", "pendulum", "oxygen",
    "nutrition", "microphone", "longitude", "kangaroo", "juxtapose", "investment",
    "hypothesis", "gigantic", "furniture", "espresso", "dandelion", "chocolate",
    "breakfast", "astronomy", "architecture", "waterfall", "vaccination", "understanding",
    "television", "saxophone", "restaurant", "quarantine", "philosophy", "metamorphosis",
    "literature", "kaleidoscope", "jurisdiction", "independence", "hydroelectric", "geography",
    "flibbertigibbet", "entrepreneur", "dysfunction", "conversation", "biotechnology", "articulation",
    "apprehension", "acknowledgment", "ziggurat", "yachtsman", "xenophobia", "wonderment",
    "vernacular", "unscrupulous", "triskaidekaphobia", "synchronization", "rhythm", "psychoanalysis",
    "ophthalmologist", "nomenclature", "misanthrope", "lexicography", "jackhammer", "interpretation",
    "hieroglyphics", "grandiloquence", "facetious", "existential", "dichotomy", "cryptocurrency",
    "bureaucracy", "aeronautics", "abstraction", "zygomorphic", "xylograph", "weltschmerz",
    "vivisection", "utilitarianism", "transubstantiation", "superfluous", "rhabdomancy", "quixotic",
    "photosynthesis", "onomatopoeia", "nephrologist", "misconception", "logorrhea", "krypton",
    "acclimatization", "zooplankton", "xylophagous", "whippoorwill", "vexillology", "unparliamentary",
    "transmogrify", "sesquipedalian", "rhinoceros", "pneumonoultramicroscopicsilicovolcanoconiosis", "overcompensate", "neuroplasticity"
  ],
  'ko': [
    "사과", "고양이", "바나나", "도넛", "사자", "코끼리", "기린", "햄스터", "가방", "칠판",
    "다람쥐", "토끼", "앵무새", "사랑", "우산", "마우스", "피자", "자전거", "휴대폰", "컴퓨터",
    "텔레비전", "식탁", "냉장고", "미술관", "도서관", "대학교", "유치원", "스포츠카", "지하철", "헬리콥터",
    "앰뷸런스", "병원", "약국", "공원", "놀이터", "영화관", "음악회", "콘서트", "박물관", "전시회",
    "도시락", "바닷가", "산책로", "비행기", "농구공", "볼링공", "장난감", "인형", "기타", "드럼",
    "마이크", "스피커", "카메라", "노트북", "계산기", "사전", "연필깎이", "책상", "의자", "칠판지우개",
    "목걸이", "귀걸이", "팔찌", "반지", "시계", "선글라스", "모자", "장갑", "스카프", "벨트",
    "손전등", "열쇠", "지갑", "가방", "우편함", "신발장", "옷걸이", "문고리", "창문", "방충망",
    "인터넷", "블루투스", "유선전화", "스마트폰", "태블릿", "프린터", "스캐너", "팩스", "커피머신", "전자레인지",
    "식기세척기", "믹서기", "토스터", "에어프라이어", "진공청소기", "건조기", "세탁기", "선풍기", "에어컨", "보일러",
    "냉장고", "냉동고", "전기밥솥", "전기포트", "인덕션", "가스레인지", "손목시계", "자동차", "오토바이", "자전거",
    "모노레일", "지하철", "트램", "택시", "버스", "트럭", "엘리베이터", "에스컬레이터", "화장실", "욕실",
    "침실", "거실", "주방", "식당", "다락방", "지하실", "차고", "정원", "옥상", "발코니",
    "아파트", "주택", "빌라", "캐슬", "궁전", "사원", "성당", "모스크", "회당", "사찰",
    "강당", "체육관", "도서관", "미술관", "박물관", "과학관", "식물원", "동물원", "수족관", "테마파크",
    "롤러코스터", "자이로드롭", "번지점프", "스카이다이빙", "패러글라이딩", "스쿠버다이빙", "서핑", "스노보드", "스키", "아이스하키",
    "농구", "야구", "축구", "골프", "테니스", "배드민턴", "탁구", "볼링", "양궁", "사격"
  ]
}